import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { Hero } from '@/components/hero'
import { Card } from '@/components/card'
import { Cards } from '@/components/cards'
import { Decoration } from '@/components/decoration'
import { LogoAnimation } from '@/components/logoanimation'
import { AccordionComponent } from '@/components/accordion'
import Introduction from '@/components/valeurs'
import Valeurs from '@/components/valeurs'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Cards/>
      {/* <Valeurs/> */}
      <AccordionComponent />
      {/*<LogoAnimation />*/}
    </>
  )
}
